name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing: 
        name: Unit testing
        permissions:
          contents: read
          packages: write
        strategy:
            matrix:
                nodejs_version: [18, 19, 20]
        #         operating_system: [ubuntu-latest, macos-latest]
                exclude:
                    - nodejs_version: 18
        #               operating_system: macos-latest
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v7

          - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.nodejs_version }}

          - name: Cache NPM dependencies 
            uses: actions/cache@v4
            with:
              path: node_modules
              key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}        

          - name: Install Dependencies
            run: npm install

          - name: Unit testing
            id: nodejs-unit-testing-step
            run: npm test

          - name: Archite Test Result
            # if failure() && (steps.nodejs-unit-testing-step.outcome == 'failure' || steps.nodejs-unit-testing-step.outcome == 'success' )
            if: always()
            uses: actions/upload-artifact@v7.0.1
            with:
              name: Mocha-Test_result
              path: test-results.xml

    code-coverage: 
        name: Code Coverage
        strategy:
            matrix:
                nodejs_version: [18, 20]
        #         operating_system: [ubuntu-latest, macos-latest]
        #         exclude:
        #           - operating_system: macos-latest
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v7

          - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.nodejs_version }}

          - name: Cache NPM dependencies 
            uses: actions/cache@v4
            with:
              path: node_modules
              key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}    

          - name: Install Dependencies
            run: npm install

            
          - name: Check Code Coverage
            continue-on-error: true
            run: npm run coverage

          - name: Archite Test Result
            uses: actions/upload-artifact@v7.0.1
            with:
              name: Code-Coverage-result
              path: coverage
              retention-days: 5

    docker:
        name: Containerization
        runs-on: ubuntu-latest
        needs : [unit-testing, code-coverage]
        permissions:
          contents: read
          packages: write
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Dockerhub Login
          uses: docker/login-action@v4.6.0
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: GHCR Login
          uses: docker/login-action@v4.6.0
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN  }}

        - name: Docker Build for testing
          uses: docker/build-push-action@v7.4.0
          with:
            context: .
            push: false
            tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

            
        - name: Docker Image Test
          run: |
            docker images
            docker run --name solar-system-app -d \
            -p 3000:3000 \
            -e MONGO_URI=$MONGO_URI \
            -e MONGO_USERNAME=$MONGO_USERNAME \
            -e MONGO_PASSWORD=$MONGO_PASSWORD \
            ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

            export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
            echo $IP

            echo Testing Image URL using wget
            wget -q -O - 127.0.0.1:3000/live | grep live

        # - name: Docker Build for Testing
        #   uses: docker/build-push-action@v7.4.0
        #   with: 
        #     context: .
        #     push: true
        #     tags: ${{ vars.DOCKER_USERNAME}}/solar-system:${{ github.sha }}

        - name: Container Registry Push
          uses: docker/build-push-action@v7.4.0
          with: 
            context: .
            push: true
            tags: 
              ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}